{
  lib,
  stdenv,
  rustPlatform,
  pkg-config,
  openssl,
  cacert,
  makeWrapper,
  installShellFiles,
  ecr-web,
  notmuch,
  isync,
  msmtp,
  version,
}:

rustPlatform.buildRustPackage (finalAttrs: {
  pname = "ecr";
  inherit version;

  src = lib.fileset.toSource {
    root = ../.;
    fileset = lib.fileset.unions [
      ../Cargo.toml
      ../Cargo.lock
      ../crates
      # A workspace member, so cargo needs it present to resolve at all. Only
      # ecr-cli is actually built, so none of the WebKitGTK closure is linked.
      ../shell
      # The integration tests build a throwaway notmuch database from these.
      ../fixtures
      # The systemd user unit, installed for whoever is not on NixOS.
      ../packaging
    ];
  };

  cargoLock.lockFile = ../Cargo.lock;

  # The desktop shell is a workspace member and pulls in the whole WebKitGTK
  # closure. A headless install must never link it, so only the CLI is built.
  cargoBuildFlags = [
    "-p"
    "ecr-cli"
  ];
  cargoTestFlags = [
    "-p"
    "ecr-core"
    "-p"
    "ecr-store"
    "-p"
    "ecr-server"
    "-p"
    "ecr-cli"
  ];

  nativeBuildInputs = [
    pkg-config
    makeWrapper
    installShellFiles
  ];
  buildInputs = [ openssl ];

  # `ecr --version` reports this instead of the Cargo version. Both channels can
  # sit at the same release number, so the revision is the only thing that
  # answers which of the two is installed.
  ECR_BUILD_VERSION = finalAttrs.version;

  # The integration tests drive the real notmuch binary against a tempdir, and
  # the doctor tests assert a healthy setup, which means all three on PATH.
  nativeCheckInputs = [
    notmuch
    isync
    msmtp
    cacert
  ];

  # `ecr oauth` gave ecr-store a reqwest with rustls, and cargo unifies that
  # feature across the workspace — so ecr-server's test client, which only ever
  # speaks plain HTTP to 127.0.0.1, now builds with TLS too. rustls loads the
  # system trust store when a client is constructed and `reqwest::Client::new()`
  # *panics* when it finds none, which a build sandbox never has: every one of
  # the 43 API tests died before making a request. Nothing here reaches the
  # network; the certificates only have to exist.
  SSL_CERT_FILE = "${cacert}/etc/ssl/certs/ca-bundle.crt";

  postInstall = ''
    mkdir -p $out/share/ecr
    cp -r ${ecr-web} $out/share/ecr/web

    ${lib.optionalString (stdenv.buildPlatform.canExecute stdenv.hostPlatform) ''
      # Generated by running the binary that was just built, so they can never
      # describe a command tree other than the one being installed. Real files
      # rather than process substitutions: installManPage takes the section
      # from the filename, and /dev/fd/63 does not have one.
      $out/bin/ecr man > ecr.1
      installManPage ecr.1

      $out/bin/ecr completions bash > ecr.bash
      $out/bin/ecr completions fish > ecr.fish
      $out/bin/ecr completions zsh > ecr.zsh
      installShellCompletion --cmd ecr \
        --bash ecr.bash --fish ecr.fish --zsh ecr.zsh
    ''}

    install -Dm644 packaging/ecr.service $out/share/doc/ecr/ecr.service

    # ecr-store shells out to these; without them on PATH `ecr doctor` fails and
    # the server refuses to start.
    #
    # $out/bin is on that list because ecr is now its own OAuth helper: an
    # mbsync config says `PassCmd "ecr oauth token <profile>"`, and mbsync is a
    # child of the server, which under a systemd user unit inherits nothing from
    # a login shell. Without this, every XOAUTH2 account fails to sync with
    # `ecr: command not found` buried in mbsync's output.
    #
    # SASL_PATH is the other half of the same failure: mbsync authenticates
    # Gmail/Outlook with XOAUTH2, whose mechanism ships in a separate plugin
    # (cyrus-sasl-xoauth2) that isync's closure does not carry. Without it the
    # plugin is never loaded and every OAuth account fails with
    # "selected SASL mechanism(s) not available".
    wrapProgram $out/bin/ecr \
      --prefix PATH : "$out/bin:${
        lib.makeBinPath [
          notmuch
          isync
          msmtp
        ]
      }" \
  '';

  meta = {
    description = "A keyboard-driven mail client for an existing notmuch maildir";
    homepage = "https://github.com/lokeshmohanty/ecr";
    license = [
      lib.licenses.mit
      lib.licenses.gpl3Plus
    ];
    mainProgram = "ecr";
    platforms = lib.platforms.unix;
  };
})
