[workspace]
resolver = "2"
members = ["crates/ecr-core", "crates/ecr-store", "crates/ecr-server", "shell"]

[workspace.package]
version = "0.1.0"
edition = "2021"
license = "MIT"

[workspace.dependencies]
ecr-core = { path = "crates/ecr-core" }
ecr-store = { path = "crates/ecr-store" }

anyhow = "1"
thiserror = "2"
serde = { version = "1", features = ["derive"] }
serde_json = "1"
toml = "0.9"
tokio = { version = "1", features = ["full"] }
tracing = "0.1"
tracing-subscriber = { version = "0.3", features = ["env-filter"] }
dirs = "6"
chrono = { version = "0.4", features = ["serde"] }
clap = { version = "4", features = ["derive"] }

[profile.dev.package."*"]
opt-level = 2
