pub mod address;
pub mod cache;
pub mod compose;
pub mod contacts;
pub mod dav;
pub mod discovery;
pub mod doctor;
pub mod error;
pub mod folders;
pub mod imap;
pub mod index;
pub mod managed;
pub mod mbsync;
pub mod mime;
pub mod msmtp;
pub mod notmuch;
pub mod notmuch_store;
pub mod oauth;
pub mod outbox;
pub mod packages;
pub mod parse;
pub mod paths;
pub mod settings;
pub mod smtp;
pub mod store;
pub mod themes;
pub mod tools;

pub use error::{Error, Result};
pub use notmuch::Notmuch;
pub use notmuch_store::NotmuchStore;
pub use paths::MailPaths;
pub use settings::ServerSettings;
pub use store::{BodyOptions, MailStore, ProgressSink};
