//! Which tools ecr drives, and who owns their configuration.
//!
//! The switch is `[packages.<id>]` in the shared `settings.toml`, and the whole
//! of it — the section, the file, the generated documentation — is written by
//! `web/src/state/settings/toml.ts`. This module reads the one part of that file
//! the server has to act on, and deliberately nothing else: the settings schema
//! stays in one language, and what crosses the boundary is pinned by a fixture
//! the web suite generates and `tests/packages_fixture.rs` parses.
//!
//! Every failure answers `self`. A file ecr cannot parse is a file whose author
//! never asked ecr to take over their mail configuration, and the cost of the
//! two mistakes is not symmetric: reading a self-managed setup as self-managed
//! is a no-op, while reading it as ecr-managed writes files nobody asked for.

use crate::error::Result;
use crate::paths::Env;
use ecr_core::doctor::ConfigKind;
use serde::Deserialize;
use std::collections::BTreeMap;
use std::path::{Path, PathBuf};

/// The documented settings file a machine that has none starts from.
///
/// Generated by `toToml` in the web client and pinned by
/// `web/src/state/settings/fixture.test.ts`, which is the only generator there
/// is: a second one written in Rust would be two files claiming to be the
/// default. `ecr account` seeds from this rather than writing a bare
/// `[packages.mbsync]` stub, because the client only replaces a settings file it
/// finds *empty* — a stub would cost the reader the documentation for good.
pub const DEFAULT_SETTINGS: &str = include_str!("../settings/default.toml");

#[derive(Debug, Clone, Copy, Default, PartialEq, Eq, Deserialize)]
pub enum Management {
    /// The machine already has a working setup. ecr reads it and never writes
    /// it.
    #[default]
    #[serde(rename = "self")]
    SelfManaged,
    /// ecr generates this file from the accounts it holds.
    #[serde(rename = "ecr")]
    Ecr,
}

impl Management {
    pub fn is_ecr(self) -> bool {
        self == Management::Ecr
    }
}

#[derive(Debug, Clone, Default, Deserialize)]
pub struct PackageConfig {
    #[serde(default)]
    pub management: Management,
}

/// Unknown package ids are kept rather than rejected. `PACKAGE_IDS` on the
/// client is a list that shrinks — imapnotify and vdirsyncer are both on their
/// way out — and a server that refused to parse a file naming one would break
/// every setup mid-upgrade.
#[derive(Debug, Clone, Default, Deserialize)]
struct SettingsFile {
    #[serde(default)]
    packages: BTreeMap<String, PackageConfig>,
}

#[derive(Debug, Clone, Default)]
pub struct Packages(BTreeMap<String, PackageConfig>);

impl Packages {
    /// Reads the shared settings file, anchored to this `Env` rather than to the
    /// process. `dirs::config_dir()` outranks a redirected `HOME`, which is the
    /// trap [`crate::paths::MailPaths::oauth_profiles`] documents — and it is
    /// worse here, because managed mode *writes*.
    pub fn load(env: &Env) -> Self {
        Self::load_from(&Self::path_in(env))
    }

    pub fn path_in(env: &Env) -> PathBuf {
        env.config_dir.join("ecr").join("settings.toml")
    }

    pub fn load_from(path: &Path) -> Self {
        match std::fs::read_to_string(path) {
            Ok(text) => Self::parse(&text),
            Err(_) => Self::default(),
        }
    }

    pub fn parse(text: &str) -> Self {
        match toml::from_str::<SettingsFile>(text) {
            Ok(file) => Self(file.packages),
            Err(err) => {
                tracing::warn!(%err, "settings.toml could not be read; every package is self-managed");
                Self::default()
            }
        }
    }

    pub fn management(&self, kind: ConfigKind) -> Management {
        self.0
            .get(kind.to_string().as_str())
            .map(|p| p.management)
            .unwrap_or_default()
    }

    pub fn is_managed(&self, kind: ConfigKind) -> bool {
        self.management(kind).is_ecr()
    }

    pub fn any_managed(&self) -> bool {
        [ConfigKind::Notmuch, ConfigKind::Mbsync, ConfigKind::Msmtp]
            .into_iter()
            .any(|kind| self.is_managed(kind))
    }

    /// Hands a package to ecr, or gives it back, in the shared settings file.
    ///
    /// The whole file belongs to the client's generator, so this replaces one
    /// value and leaves every other byte alone — the same discipline `withValue`
    /// holds to on the other side, and for the same reason: somebody has
    /// commented and reordered that file to their taste.
    pub fn set_management(env: &Env, kind: ConfigKind, management: Management) -> Result<PathBuf> {
        Self::set_management_at(&Self::path_in(env), kind, management)
    }

    /// The same, against a settings file that has already been resolved — which
    /// is what the server has, out of the `MailPaths` it was opened with. Going
    /// back to a process `Env` there would let a rooted test write the
    /// developer's own settings file, and this one *writes*.
    pub fn set_management_at(
        path: &std::path::Path,
        kind: ConfigKind,
        management: Management,
    ) -> Result<PathBuf> {
        let path = path.to_path_buf();
        let existing = std::fs::read_to_string(&path).unwrap_or_else(|_| DEFAULT_SETTINGS.into());
        let updated = with_management(&existing, kind, management);

        if let Some(parent) = path.parent() {
            std::fs::create_dir_all(parent)?;
        }
        let staging = path.with_extension("toml.ecr-staging");
        std::fs::write(&staging, updated)?;
        std::fs::rename(&staging, &path)?;
        Ok(path)
    }
}

/// The edit itself, as text in and text out so it can be tested without a disk.
pub fn with_management(text: &str, kind: ConfigKind, management: Management) -> String {
    let header = format!("[packages.{kind}]");
    let value = format!(
        "management = \"{}\"",
        match management {
            Management::SelfManaged => "self",
            Management::Ecr => "ecr",
        }
    );

    let mut lines: Vec<String> = text.lines().map(str::to_string).collect();
    let Some(at) = lines.iter().position(|l| l.trim() == header) else {
        // No section for this package at all, which is a settings file older
        // than the tool. Append rather than regenerate: the rest of the file is
        // the reader's.
        if !lines.last().map(|l| l.is_empty()).unwrap_or(true) {
            lines.push(String::new());
        }
        lines.push(header);
        lines.push(value);
        lines.push(String::new());
        return lines.join("\n");
    };

    // Only until the next section: a `management` key belonging to some other
    // package is not this one's.
    let end = lines
        .iter()
        .skip(at + 1)
        .position(|l| l.trim_start().starts_with('['))
        .map(|offset| at + 1 + offset)
        .unwrap_or(lines.len());

    match lines[at + 1..end]
        .iter()
        .position(|l| l.trim_start().starts_with("management"))
    {
        Some(offset) => lines[at + 1 + offset] = value,
        None => lines.insert(at + 1, value),
    }

    let mut out = lines.join("\n");
    if text.ends_with('\n') && !out.ends_with('\n') {
        out.push('\n');
    }
    out
}

#[cfg(test)]
mod tests {
    use super::*;

    #[test]
    fn an_absent_file_is_entirely_self_managed() {
        let packages = Packages::load_from(Path::new("/nonexistent/ecr/settings.toml"));
        assert!(!packages.any_managed());
        assert_eq!(
            packages.management(ConfigKind::Mbsync),
            Management::SelfManaged
        );
    }

    #[test]
    fn a_managed_package_is_read_per_tool() {
        let packages = Packages::parse(
            r#"
            [packages.mbsync]
            management = "ecr"
            config = ""

            [packages.msmtp]
            management = "self"
            config = ""
            "#,
        );

        assert!(packages.is_managed(ConfigKind::Mbsync));
        assert!(!packages.is_managed(ConfigKind::Msmtp));
        assert!(!packages.is_managed(ConfigKind::Notmuch));
        assert!(packages.any_managed());
    }

    /// The client writes each config as a TOML multi-line string, and the
    /// section is surrounded by generated documentation. Reading it must not
    /// depend on any of that.
    #[test]
    fn the_generated_shape_of_the_file_parses() {
        let packages = Packages::parse(
            r#"
# ------------------------------------------------------------------
# Packages
# ------------------------------------------------------------------

[preferences]
start_query = "tag:inbox"

# mbsync (isync) — syncs IMAP to the maildir (isyncrc)
[packages.mbsync]
management = "ecr"
config = """
IMAPAccount main
User alice@example.com
PassCmd "ecr oauth token main"
"""
"#,
        );

        assert!(packages.is_managed(ConfigKind::Mbsync));
    }

    /// A package the server has never heard of must not cost it the ones it has.
    #[test]
    fn an_unknown_package_id_does_not_break_the_file() {
        let packages = Packages::parse(
            r#"
            [packages.vdirsyncer]
            management = "ecr"

            [packages.notmuch]
            management = "ecr"
            "#,
        );

        assert!(packages.is_managed(ConfigKind::Notmuch));
    }

    /// The asymmetry that governs this module: reading a self-managed setup as
    /// self-managed costs nothing, and reading it as ecr-managed writes files
    /// nobody asked for.
    #[test]
    fn the_shipped_default_parses_and_manages_nothing() {
        let packages = Packages::parse(DEFAULT_SETTINGS);
        assert!(!packages.any_managed());
    }

    #[test]
    fn switching_a_package_leaves_every_other_byte_alone() {
        let before = DEFAULT_SETTINGS;
        let after = with_management(before, ConfigKind::Mbsync, Management::Ecr);

        assert!(Packages::parse(&after).is_managed(ConfigKind::Mbsync));
        assert!(!Packages::parse(&after).is_managed(ConfigKind::Msmtp));
        assert_eq!(
            before.lines().count(),
            after.lines().count(),
            "a line was added or lost"
        );
        // The generated documentation is still there.
        assert!(after.contains("# ecr settings"));
    }

    #[test]
    fn switching_back_is_the_same_edit_in_reverse() {
        let on = with_management(DEFAULT_SETTINGS, ConfigKind::Notmuch, Management::Ecr);
        let off = with_management(&on, ConfigKind::Notmuch, Management::SelfManaged);

        assert_eq!(off, DEFAULT_SETTINGS);
    }

    /// A settings file written before this package existed.
    #[test]
    fn a_missing_section_is_appended_rather_than_regenerating_the_file() {
        let text = "[general]\nstart_query = \"tag:inbox\"\n";
        let after = with_management(text, ConfigKind::Msmtp, Management::Ecr);

        assert!(after.starts_with(text), "{after}");
        assert!(Packages::parse(&after).is_managed(ConfigKind::Msmtp));
    }

    #[test]
    fn a_management_key_in_another_section_is_not_mistaken_for_this_one() {
        let text = "[packages.mbsync]\nmanagement = \"self\"\n\n[packages.msmtp]\nconfig = \"\"\n";
        let after = with_management(text, ConfigKind::Msmtp, Management::Ecr);
        let packages = Packages::parse(&after);

        assert!(packages.is_managed(ConfigKind::Msmtp));
        assert!(
            !packages.is_managed(ConfigKind::Mbsync),
            "the wrong section was edited: {after}"
        );
    }

    #[test]
    fn an_unparsable_file_is_self_managed_rather_than_a_guess() {
        assert!(!Packages::parse("this is not toml {{{ [packages.mbsync").any_managed());
        assert!(!Packages::parse("[packages.mbsync]\nmanagement = 7\n").any_managed());
        assert!(!Packages::parse("[packages.mbsync]\nmanagement = \"maybe\"\n").any_managed());
    }
}
