//! Files ecr generates and owns.
//!
//! Everything managed mode writes goes through [`write`], which is the whole of
//! ecr's licence to touch a configuration file. Three properties matter, and
//! each of them is a failure this codebase has already paid for somewhere else:
//!
//! * **The write is atomic.** Rendered into a `.staging` sibling and renamed, so
//!   a tool reading the file never sees half of one — and, as `write_stub` in
//!   the test support records, the inode that is read is never the inode that
//!   was written.
//! * **A generated file says so, and carries the digest of its own body.** A
//!   reader who edited one gets their edit backed up and named, rather than
//!   silently overwritten on the next `ecr account apply`. ecr owning a file is
//!   a thing the reader switched on; it is not a claim on whatever they do
//!   afterwards.
//! * **An unchanged file is not rewritten.** Apply is idempotent and runs on
//!   every account change, and mbsync, msmtp and notmuch are not the only things
//!   watching a mail directory's mtimes.

pub mod accounts;
pub mod render;

pub use accounts::Accounts;
pub use render::Layout;

use crate::error::Result;
use sha2::{Digest, Sha256};
use std::path::{Path, PathBuf};

const GENERATED_BY: &str =
    "# Generated by ecr — every edit below is lost on the next `ecr account apply`.";
const FROM_PREFIX: &str = "# It is generated from ";
const HASH_PREFIX: &str = "# ecr-hash: ";

#[derive(Debug, Clone, PartialEq, Eq)]
pub enum Outcome {
    /// The file was already exactly this. Nothing was touched.
    Unchanged,
    Created,
    Replaced,
    /// The file had been edited by hand, so it was moved aside first.
    ReplacedAfterBackup(PathBuf),
}

impl Outcome {
    pub fn wrote(&self) -> bool {
        !matches!(self, Outcome::Unchanged)
    }
}

/// Writes `body` to `path` as a file ecr owns.
///
/// `source` names where the content came from, in the reader's terms — the file
/// they *can* edit. A generated file that does not say what to edit instead is
/// a dead end.
pub fn write(path: &Path, body: &str, source: &str) -> Result<Outcome> {
    write_with_mode(path, body, source, 0o600)
}

/// As [`write`], with the permissions spelled out. The `post-new` hook is a
/// program notmuch execs, so it is the one generated file that is 0700.
pub fn write_with_mode(path: &Path, body: &str, source: &str, mode: u32) -> Result<Outcome> {
    let contents = render(body, source);

    let existing = std::fs::read_to_string(path).ok();
    let outcome = match &existing {
        None => Outcome::Created,
        Some(text) if text == &contents => return Ok(Outcome::Unchanged),
        Some(text) if was_edited(text) => {
            let backup = backup_path(path);
            std::fs::rename(path, &backup)?;
            Outcome::ReplacedAfterBackup(backup)
        }
        Some(_) => Outcome::Replaced,
    };

    if let Some(parent) = path.parent() {
        std::fs::create_dir_all(parent)?;
    }

    // Beside the target rather than in a temp directory: rename is only atomic
    // within a filesystem, and $TMPDIR is very often a different one.
    let staging = staging_path(path);
    std::fs::write(&staging, &contents)?;
    restrict(&staging, mode)?;
    std::fs::rename(&staging, path)?;

    Ok(outcome)
}

/// The bytes [`write`] would produce, without writing them.
///
/// `ecr account import` shows this against what is already on disk, and doctor
/// compares it to decide whether the rendered files have drifted from the
/// accounts they came from.
pub fn render(body: &str, source: &str) -> String {
    let body = if body.ends_with('\n') || body.is_empty() {
        body.to_string()
    } else {
        format!("{body}\n")
    };

    let header = format!(
        "{GENERATED_BY}\n{FROM_PREFIX}{source}, which is the file to edit.\n{HASH_PREFIX}{}\n\n",
        digest(&body)
    );

    // A shebang is only a shebang on the first line: the kernel reads two bytes
    // at offset zero and nothing else. The `post-new` hook is a program notmuch
    // execs, so the header goes *under* its first line — and `body_of` takes the
    // header out by matching those lines wherever they are, rather than by
    // assuming they come first.
    match body.starts_with("#!") {
        true => match body.split_once('\n') {
            Some((shebang, rest)) => format!("{shebang}\n{header}{rest}"),
            None => format!("{body}\n{header}"),
        },
        false => format!("{header}{body}"),
    }
}

/// Whether a file on disk no longer matches the digest it was written with.
///
/// A file with no digest line at all was not written by ecr — a self-managed
/// config at a path managed mode has just been pointed at, say — and counts as
/// edited, which is the answer that backs it up rather than destroying it.
pub fn was_edited(text: &str) -> bool {
    let Some(recorded) = text
        .lines()
        .find_map(|line| line.strip_prefix(HASH_PREFIX))
        .map(str::trim)
    else {
        return true;
    };

    match body_of(text) {
        Some(body) => digest(&body) != recorded,
        None => true,
    }
}

/// The generated body, with ecr's header taken back out.
///
/// By matching the header's own lines rather than by counting from the top,
/// because a script carries its shebang above them.
pub fn body_of(text: &str) -> Option<String> {
    let lines: Vec<&str> = text.split('\n').collect();
    let hash_at = lines.iter().position(|l| l.starts_with(HASH_PREFIX))?;

    let mut kept: Vec<&str> = Vec::with_capacity(lines.len());
    for (index, line) in lines.iter().enumerate() {
        let is_header = index == hash_at
            || (*line == GENERATED_BY)
            || line.starts_with(FROM_PREFIX)
            // The blank line the header ends with.
            || (index == hash_at + 1 && line.is_empty());
        if !is_header {
            kept.push(line);
        }
    }

    Some(kept.join("\n"))
}

fn digest(body: &str) -> String {
    let mut out = String::with_capacity(64);
    for byte in Sha256::digest(body.as_bytes()) {
        out.push_str(&format!("{byte:02x}"));
    }
    out
}

fn staging_path(path: &Path) -> PathBuf {
    let mut name = path.file_name().unwrap_or_default().to_os_string();
    name.push(".ecr-staging");
    path.with_file_name(name)
}

fn backup_path(path: &Path) -> PathBuf {
    let stamp = std::time::SystemTime::now()
        .duration_since(std::time::UNIX_EPOCH)
        .map(|d| d.as_secs())
        .unwrap_or(0);

    let mut name = path.file_name().unwrap_or_default().to_os_string();
    name.push(format!(".ecr-backup.{stamp}"));
    path.with_file_name(name)
}

/// Mode 0600.
///
/// msmtp refuses to read a configuration that anyone else can read, which is the
/// right instinct for a file naming how to reach a mailbox, and these carry the
/// command that mints an access token besides.
#[cfg(unix)]
fn restrict(path: &Path, mode: u32) -> Result<()> {
    use std::os::unix::fs::PermissionsExt;
    std::fs::set_permissions(path, std::fs::Permissions::from_mode(mode))?;
    Ok(())
}

#[cfg(not(unix))]
fn restrict(_path: &Path, _mode: u32) -> Result<()> {
    Ok(())
}

#[cfg(test)]
mod tests {
    use super::*;

    fn write_at(dir: &Path, body: &str) -> (PathBuf, Outcome) {
        let path = dir.join("isyncrc");
        let outcome = write(&path, body, "accounts.toml").unwrap();
        (path, outcome)
    }

    #[test]
    fn a_generated_file_names_what_to_edit_instead() {
        let dir = tempfile::tempdir().unwrap();
        let (path, outcome) = write_at(dir.path(), "Channel main\n");

        let text = std::fs::read_to_string(&path).unwrap();
        assert_eq!(outcome, Outcome::Created);
        assert!(text.contains("Generated by ecr"), "{text}");
        assert!(text.contains("accounts.toml"), "{text}");
        assert!(text.ends_with("Channel main\n"), "{text}");
    }

    #[test]
    fn writing_the_same_body_again_changes_nothing() {
        let dir = tempfile::tempdir().unwrap();
        let (path, _) = write_at(dir.path(), "Channel main\n");
        let before = std::fs::metadata(&path).unwrap().modified().unwrap();

        assert_eq!(write_at(dir.path(), "Channel main\n").1, Outcome::Unchanged);
        assert_eq!(
            std::fs::metadata(&path).unwrap().modified().unwrap(),
            before
        );
    }

    #[test]
    fn a_new_body_replaces_a_file_ecr_wrote() {
        let dir = tempfile::tempdir().unwrap();
        write_at(dir.path(), "Channel main\n");
        let (path, outcome) = write_at(dir.path(), "Channel work\n");

        assert_eq!(outcome, Outcome::Replaced);
        assert!(std::fs::read_to_string(&path).unwrap().contains("work"));
    }

    /// The reader edited a file ecr owns. That is a mistake ecr should name, not
    /// one it should destroy the evidence of.
    #[test]
    fn an_edited_file_is_moved_aside_rather_than_clobbered() {
        let dir = tempfile::tempdir().unwrap();
        let (path, _) = write_at(dir.path(), "Channel main\n");

        let edited = std::fs::read_to_string(&path).unwrap() + "Patterns *\n";
        std::fs::write(&path, &edited).unwrap();

        let (_, outcome) = write_at(dir.path(), "Channel main\n");
        let Outcome::ReplacedAfterBackup(backup) = outcome else {
            panic!("expected a backup, got {outcome:?}");
        };
        assert_eq!(std::fs::read_to_string(&backup).unwrap(), edited);
        assert!(std::fs::read_to_string(&path)
            .unwrap()
            .ends_with("Channel main\n"));
    }

    /// A file ecr did not write carries no digest at all, and taking that for
    /// "unedited" would let managed mode consume somebody's own config the first
    /// time it was pointed at one.
    #[test]
    fn a_file_ecr_never_wrote_counts_as_edited() {
        let dir = tempfile::tempdir().unwrap();
        let path = dir.path().join("isyncrc");
        std::fs::write(&path, "IMAPAccount mine\nUser me@example.com\n").unwrap();

        let outcome = write(&path, "Channel main\n", "accounts.toml").unwrap();
        let Outcome::ReplacedAfterBackup(backup) = outcome else {
            panic!("expected a backup, got {outcome:?}");
        };
        assert!(std::fs::read_to_string(backup).unwrap().contains("me@"));
    }

    #[test]
    fn the_digest_covers_the_body_and_not_the_header() {
        let one = render("Channel main\n", "accounts.toml");
        let two = render("Channel main\n", "somewhere else entirely");

        assert!(!was_edited(&one));
        assert!(!was_edited(&two));
        assert_eq!(body_of(&one).as_deref(), Some("Channel main\n"));
    }

    /// A shebang has to stay on line one, and the digest still has to cover it.
    #[test]
    fn a_script_keeps_its_shebang_first() {
        let text = render("#!/bin/sh\nnotmuch tag -new -- tag:new\n", "accounts.toml");

        assert!(text.starts_with("#!/bin/sh\n"), "{text}");
        assert!(text.contains("Generated by ecr"), "{text}");
        assert!(!was_edited(&text));
        assert_eq!(
            body_of(&text).as_deref(),
            Some("#!/bin/sh\nnotmuch tag -new -- tag:new\n")
        );
    }

    #[test]
    fn an_edited_script_is_still_caught() {
        let text = render("#!/bin/sh\nnotmuch tag -new -- tag:new\n", "accounts.toml");
        let edited = text.replace("-new --", "+mine -new --");

        assert!(was_edited(&edited));
    }

    #[cfg(unix)]
    #[test]
    fn a_hook_can_be_written_executable() {
        use std::os::unix::fs::PermissionsExt;

        let dir = tempfile::tempdir().unwrap();
        let path = dir.path().join("post-new");
        write_with_mode(&path, "#!/bin/sh\nexit 0\n", "accounts.toml", 0o700).unwrap();

        let mode = std::fs::metadata(&path).unwrap().permissions().mode();
        assert_eq!(mode & 0o777, 0o700, "{mode:o}");
    }

    #[test]
    fn a_body_without_a_trailing_newline_gets_one() {
        assert!(render("Channel main", "accounts.toml").ends_with("Channel main\n"));
    }

    #[cfg(unix)]
    #[test]
    fn a_generated_file_is_readable_only_by_its_owner() {
        use std::os::unix::fs::PermissionsExt;

        let dir = tempfile::tempdir().unwrap();
        let (path, _) = write_at(dir.path(), "account main\n");
        let mode = std::fs::metadata(&path).unwrap().permissions().mode();

        assert_eq!(mode & 0o777, 0o600, "{mode:o}");
    }

    #[test]
    fn nothing_is_left_behind_beside_the_file() {
        let dir = tempfile::tempdir().unwrap();
        write_at(dir.path(), "Channel main\n");

        let names: Vec<_> = std::fs::read_dir(dir.path())
            .unwrap()
            .flatten()
            .map(|e| e.file_name().to_string_lossy().to_string())
            .collect();
        assert_eq!(names, vec!["isyncrc"]);
    }
}
